# Generated by Django 3.0.10 on 2020-10-07 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testcase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestcaseStep',
            fields=[
                ('id_primary', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('id_testcase_step', models.CharField(max_length=10)),
                ('testcase_step_title', models.CharField(max_length=100)),
                ('testcase_step_status', models.CharField(max_length=100)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcase_steps', to='testcase.Testcase')),
            ],
        ),
    ]
