# Generated by Django 3.0.10 on 2020-10-07 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feature', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id_primary', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('os_name', models.CharField(max_length=50)),
                ('os_version', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=50)),
                ('platform_architecture', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=30)),
                ('host', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('environment', models.CharField(max_length=10)),
                ('browser_name', models.CharField(max_length=50)),
                ('browser_version', models.CharField(max_length=50)),
                ('headless_mode', models.CharField(max_length=50)),
                ('awsdev', models.CharField(max_length=50)),
                ('java_version', models.CharField(max_length=50)),
                ('jvm_version', models.CharField(max_length=50)),
                ('jvm_vendor', models.CharField(max_length=100)),
                ('webdriver_version', models.CharField(max_length=50)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environment', to='feature.Feature')),
            ],
        ),
    ]
